---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:1.10.3
  commands:
  - KERNEL_CHECK=0 dapper ci
  volumes:
  - name: socket
    path: /var/run/docker.sock

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
