#!/bin/bash
set -ex

cd $(dirname $0)/..

source ./scripts/version

CHECKSUM="dist/checksums.txt"
rm -f $CHECKSUM

FILELIST="
initrd
sveilos.ipxe
sveilos.iso
rootfs.tar.gz
vmlinuz
sveilos-aliyun.vhd
sveilos-cloudstack.img
sveilos-digitalocean.img
sveilos-openstack.img
sveilos-pingan.img
sveilos-gce.tar.gz
sveilos-raspberry-pi64.zip
sveilos-4glte.iso
sveilos-hyperv.iso
sveilos-proxmoxve.iso
sveilos-proxmoxve-autoformat.iso
sveilos-vmware.iso
sveilos-vmware-autoformat.iso
sveilos-vmware.vmdk
"

rm -rf dist/checksums && mkdir -p dist/checksums
pushd dist/checksums
for file in $FILELIST; do
    curl -sSL -o $file https://github.com/rancher/os/releases/download/$VERSION/$file
    for algo in sha256 md5; do
        echo "$algo: $(${algo}sum $file)" >> ../../$CHECKSUM
    done
done
popd

echo "github-release upload --user boy12371 --repo os --tag ${VERSION} --file $CHECKSUM --name checksums.txt"
echo "gsutil cp $CHECKSUM gs://releases.rancher.com/os/latest/checksums.txt"
echo "gsutil cp $CHECKSUM gs://releases.rancher.com/os/$VERSION/checksums.txt"
