#!/bin/bash
set -ex

cd $(dirname $0)/..

touch .make-proxmoxve

source ./scripts/version
./scripts/release-build

touch dist/publish.sh dist/publish_gss_${VERSION}.sh dist/publish_gss_latest.sh
chmod 755 dist/publish.sh dist/publish_gss_${VERSION}.sh dist/publish_gss_latest.sh

if [ "$OS_AUTOFORMAT" = "true" ]; then
    echo "gsutil cp dist/artifacts/sveilos.iso gs://releases.rancher.com/os/latest/proxmoxve/sveilos-autoformat.iso" >> ./dist/publish_gss_latest.sh
    echo "gsutil cp dist/artifacts/sveilos.iso gs://releases.rancher.com/os/${VERSION}/proxmoxve/sveilos-autoformat.iso" >> ./dist/publish_gss_${VERSION}.sh
    echo "github-release upload --user boy12371 --repo os --tag ${VERSION} --file dist/artifacts/sveilos.iso --name sveilos-proxmoxve-autoformat.iso" >> dist/publish.sh
    exit 0
fi

for file in $(ls dist/artifacts/); do
    case $file in
        "initrd-"*)
            echo "gsutil cp dist/artifacts/${file} gs://releases.rancher.com/os/latest/proxmoxve/initrd" >> ./dist/publish_gss_latest.sh
            echo "gsutil cp dist/artifacts/${file} gs://releases.rancher.com/os/${VERSION}/proxmoxve/initrd" >> ./dist/publish_gss_${VERSION}.sh
            ;;
        "sveilos.iso" | "rootfs.tar.gz")
            echo "gsutil cp dist/artifacts/${file} gs://releases.rancher.com/os/latest/proxmoxve/${file}" >> ./dist/publish_gss_latest.sh
            echo "gsutil cp dist/artifacts/${file} gs://releases.rancher.com/os/${VERSION}/proxmoxve/${file}" >> ./dist/publish_gss_${VERSION}.sh
            ;;
    esac
done

echo "github-release upload --user boy12371 --repo os --tag ${VERSION} --file dist/artifacts/sveilos.iso --name sveilos-proxmoxve.iso" >> dist/publish.sh
